export const SERVICE_NAME = {
  AE: import.meta.env.VITE_CWINGS_UAE,
  OM: import.meta.env.VITE_CWINGS_OMN,
  LB: import.meta.env.VITE_CWINGS_LBN,
  KE: import.meta.env.VITE_CWINGS_KEN,
  BH: import.meta.env.VITE_CWINGS_BHR,
  EG: import.meta.env.VITE_CWINGS_EGY,
  JO: import.meta.env.VITE_CWINGS_JOR,
  SA: import.meta.env.VITE_CWINGS_KSA,
  KW: import.meta.env.VITE_CWINGS_KWT,
  PK: import.meta.env.VITE_CWINGS_PAK,
  QA: import.meta.env.VITE_CWINGS_QAT,
  GE: import.meta.env.VITE_CWINGS_GEO,
};

export const CWINGS = {
  DEV: {
    AE: import.meta.env.VITE_CWINGS_DEV_UAE,
    OM: import.meta.env.VITE_CWINGS_DEV_OMN,
    LB: import.meta.env.VITE_CWINGS_DEV_LBN,
    KE: import.meta.env.VITE_CWINGS_DEV_KEN,
    BH: import.meta.env.VITE_CWINGS_DEV_BHR,
    EG: import.meta.env.VITE_CWINGS_DEV_EGY,
    JO: import.meta.env.VITE_CWINGS_DEV_JOR,
    SA: import.meta.env.VITE_CWINGS_DEV_KSA,
    KW: import.meta.env.VITE_CWINGS_DEV_KWT,
    PK: import.meta.env.VITE_CWINGS_DEV_PAK,
    QA: import.meta.env.VITE_CWINGS_DEV_QAT,
    GE: import.meta.env.VITE_CWINGS_DEV_GEO,
  },
  TEST: {
    AE: import.meta.env.VITE_CWINGS_TEST_UAE,
    OM: import.meta.env.VITE_CWINGS_TEST_OMN,
    LB: import.meta.env.VITE_CWINGS_TEST_LBN,
    KE: import.meta.env.VITE_CWINGS_TEST_KEN,
    BH: import.meta.env.VITE_CWINGS_TEST_BHR,
    EG: import.meta.env.VITE_CWINGS_TEST_EGY,
    JO: import.meta.env.VITE_CWINGS_TEST_JOR,
    SA: import.meta.env.VITE_CWINGS_TEST_KSA,
    KW: import.meta.env.VITE_CWINGS_TEST_KWT,
    PK: import.meta.env.VITE_CWINGS_TEST_PAK,
    QA: import.meta.env.VITE_CWINGS_TEST_QAT,
    GE: import.meta.env.VITE_CWINGS_TEST_GEO,
  },
  PROD: {
    AE: import.meta.env.VITE_CWINGS_PROD_UAE,
    OM: import.meta.env.VITE_CWINGS_PROD_OMN,
    LB: import.meta.env.VITE_CWINGS_PROD_LBN,
    KE: import.meta.env.VITE_CWINGS_PROD_KEN,
    BH: import.meta.env.VITE_CWINGS_PROD_BHR,
    EG: import.meta.env.VITE_CWINGS_PROD_EGY,
    JO: import.meta.env.VITE_CWINGS_PROD_JOR,
    SA: import.meta.env.VITE_CWINGS_PROD_KSA,
    KW: import.meta.env.VITE_CWINGS_PROD_KWT,
    PK: import.meta.env.VITE_CWINGS_PROD_PAK,
    QA: import.meta.env.VITE_CWINGS_PROD_QAT,
    GE: import.meta.env.VITE_CWINGS_PROD_GEO,
  },
};
